### ISSUE TITLE
[Bug]:  the sponsor ad is being covered by the tools section and is not visible at all 

### ISSUE THREAD

**Issue by Amanghvxh** [juxtopposed/realtimecolors#102] opened 2024-01-09 20:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 the sponsor ad is being covered by the tools section and is not visible at all 

### Reproduction Steps

 the sponsor ad is being covered by the tools section and is not visible at all 

### Expected behavior

 the sponsor ad is being covered by the tools section and is not visible at all 

### Screenshots

 the sponsor ad is being covered by the tools section and is not visible at all 

### Device Info

 the sponsor ad is being covered by the tools section and is not visible at all 

### Additional context

 the sponsor ad is being covered by the tools section and is not visible at all

**Comment by juxtopposed** [comment] 2024-01-09 20:48
Thanks for reporting. This is not a bug. It will be addressed in the next update.

**Closed as completed by juxtopposed** 2024-01-09 20:48 UTC
Labels: bug
