### ISSUE TITLE
Locked background changes when switching from dark to light to dark

### ISSUE THREAD

**Issue by ModProg** [juxtopposed/realtimecolors#38] opened 2023-07-20 21:10 UTC
**Describe the bug**
A locked background resets when switching from dark to light and back.

**To Reproduce**
1. Go to https://realtimecolors.com/?colors=e5f0fa-0f1419-0fb5ff-0b243d-ffb44c
2. Click on "Dark/Light" twice
4. Background color changed.

**Expected behavior**
Background should go back to what it was.

**Screenshots**
From:
![grafik](https://github.com/juxtopposed/realtimecolors/assets/11978847/26887dbc-6073-44e3-b9eb-76b72104978b)

To:
![grafik](https://github.com/juxtopposed/realtimecolors/assets/11978847/4980be96-e464-4819-92c9-21fa2a2b856c)

Back to:
![grafik](https://github.com/juxtopposed/realtimecolors/assets/11978847/4d9e2f68-c3a3-4994-9b60-5f33791fb6aa)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 115

**Comment by scorixear** [comment] 2023-07-21 15:04
Duplicate of #23

**Comment by juxtopposed** [comment] 2023-07-28 17:59
Hey there, this should be updated. Check it out!

**Closed by juxtopposed** 2023-07-28 17:59 UTC
Labels: duplicate
